### ISSUE TITLE
Is this adapter still maintained?

### ISSUE THREAD

**Issue by mcm1957** [Bannsaenger/ioBroker.extron#3]
@Bannsaenger 
Please let us know whether this adapter is still developed / maintained.
There has not been any recent activity.

If this adapter is not maintained any more, please advise whether ist OK to remove it from ioBroker repositories.

**Comment by Bannsaenger** [comment]
Currently i am adding some features and bring it to >= admin 5
Will soon be a candidate to stable.

**Comment by mcm1957** [comment]
Thanks for the info.
